name: Build & Deploy

on: [push]

jobs:
  buildWebGL:
    name: Build and deploy to itch.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard
      
      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-WebGL
          restore-keys: |
            Library-build-
            Library-
      
      # - name: Unity Build WebGL
        # uses: game-ci/unity-builder@v2
        # id: unityBuildWebGL
        # env:
          # UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        # with:
          # versioning: Semantic
          # targetPlatform: WebGL
        
      - name: Unity Build Windows
        uses: game-ci/unity-builder@v2
        id: unityBuildWindows
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          versioning: Semantic
          targetPlatform: StandaloneWindows        
          
      - name: Print Version Number
        run:  echo Project Version ${{ steps.unityBuildWindows.outputs.buildVersion }}        

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-StandaloneWindows
          path: build/StandaloneWindows/StandaloneWindows

      - name: Butler Deploy
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: falling-blocks
          ITCH_USER: Exenter
          PACKAGE: build/StandaloneWindows/StandaloneWindows
          VERSION: ${{ steps.unityBuildWindows.outputs.buildVersion }}